
sudo: required
dist: trusty
language: generic

env:
  global:
    - UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/kuka-isir/rtt_lwr/rtt_lwr-2.0/lwr_utils/config/rtt_ros_integration-2.9.rosinstall
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - BEFORE_SCRIPT="source <(curl -s https://raw.githubusercontent.com/ahoarau/rtt_ros_integration-build/master/get_latest_orocos_toolchain.sh)"
    - NOT_TEST_BUILD=true
    - CATKIN_PARALLEL_JOBS="-p4 --cmake-args -DCMAKE_BUILD_TYPE=Release -DENABLE_MQ=ON -DENABLE_CORBA=ON --"
    - ROS_PARALLEL_JOBS="-j4"
    - DOCKER_RUN_OPTS="-v $HOME/install:/root/catkin_ws/install"
    - ADDITIONAL_DEBS="curl"
    
  matrix:
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="jade"
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="lunar"

install:
  - git clone https://github.com/ipa-mdl/industrial_ci -b fix/install-space .ci_config
script:
  - mkdir $HOME/install
  - travis_wait 30 source .ci_config/travis.sh
  - tar -czf $HOME/rtt_ros_integration-2.9-$ROS_DISTRO-$(uname -m)-$(lsb_release -cs)-release.tar.gz -C $HOME/install/ .

deploy:
  provider: releases
  api-key: 
      secure: $API_TOKEN
  file: $HOME/rtt_ros_integration-2.9-$ROS_DISTRO-$(uname -m)-$(lsb_release -cs)-release.tar.gz
  skip_cleanup: true
  on:
    branch: master
